apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo 
    spec:
      containers:
        - name: demo 
          image: dhlpocregistry.azurecr.io/demo
          ports:
          - containerPort: 7777